server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1 #连接redis的主机ip
    port: 6379
    password: 123456
    timeout: 1000 #连接超时时间
    jedis:
      pool:
        max-active: 30 #给定时间内最大的连接数，使用负值表示没有限制
        max-idle: 10 #最大空闲连接数
        min-idle: 1 #最小空闲连接数
        max-wait: -1 #连接池最大等待时间，-1表示没有限制